services:
  loki:
    image: grafana/loki:3.0.0
    container_name: fintra_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-data:/loki
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: fintra_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=your_secure_admin_password_here
    volumes:
      - ./grafana-data:/var/lib/grafana
    restart: always
