name: FinTra CI/CD Build on Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy & Build on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/fintra/finance-tracker
            git pull origin main

            cd frontend
            npm install
            npm run build
            
            sudo cp -r dist/* /var/www/html/fintra/
            

            cd ../backend
            npm install
            pm2 delete fintra-api || true
            pm2 start server.js --name fintra-api

            sudo chown -R www-data:www-data /var/www/html/fintra/
            sudo systemctl reload nginx